// packages/ctsj-microfrontends-vue-mixing-app/src/self1.vue
<template>
	<a-card title="Card Title">
		<a-card-grid style="width:25%;text-align:center">
			Content
		</a-card-grid>
		<a-card-grid style="width:25%;text-align:center" :hoverable="false">
			Content
		</a-card-grid>
		<a-card-grid style="width:25%;text-align:center">
			Content
		</a-card-grid>
		<a-card-grid style="width:25%;text-align:center">
			Content
		</a-card-grid>
		<a-card-grid style="width:25%;text-align:center">
			Content
		</a-card-grid>
		<a-card-grid style="width:25%;text-align:center">
			Content
		</a-card-grid>
		<a-card-grid style="width:25%;text-align:center">
			Content
		</a-card-grid>
		<a-card-grid style="width:25%;text-align:center">
			Content
		</a-card-grid>
	</a-card>
</template>

<script>
  export default {

  };
</script>

// packages/ctsj-microfrontends-react-mixing-app/src/self1.jsx
import React from 'react';
import { Card } from 'antd';

const gridStyle = {
  width: '25%',
  textAlign: 'center',
};

export default () => (
  <Card title="Card Title">
    <Card.Grid style={gridStyle}>Content</Card.Grid>
    <Card.Grid hoverable={false} style={gridStyle}>
      Content
    </Card.Grid>
    <Card.Grid style={gridStyle}>Content</Card.Grid>
    <Card.Grid style={gridStyle}>Content</Card.Grid>
    <Card.Grid style={gridStyle}>Content</Card.Grid>
    <Card.Grid style={gridStyle}>Content</Card.Grid>
    <Card.Grid style={gridStyle}>Content</Card.Grid>
  </Card>
);
