// packages/ctsj-microfrontends-vue-basiclayout-app/src/basiclayout.vue
<template>
  <div class="Wrap">
    <div class="Fixed">
      <div class="Menu">
        <a-menu
          :default-selected-keys="['1']"
          :default-open-keys="['sub1']"
          mode="inline"
          theme="dark"
          :inline-collapsed="collapsed"
        >
          <a-menu-item key="1" v-on:click="push('/vue_system/vue_menu')">
            <span>菜单管理</span>
          </a-menu-item>
          <a-menu-item key="2" v-on:click="push('/vue_system/vue_role')">
            <span>角色管理</span>
          </a-menu-item>
          <a-menu-item key="3" v-on:click="push('/vue_system/vue_department')">
            <span>部门管理</span>
          </a-menu-item>
          <a-sub-menu key="4">
            <span slot="title">
              <span>统计</span>
            </span>
            <a-menu-item key="11" v-on:click="push('/vue_system/vue_statistics/total')">汇总统计</a-menu-item>
            <a-menu-item key="22" v-on:click="push('/vue_system/vue_statistics/person')">人员统计</a-menu-item>
            <a-menu-item key="33" v-on:click="push('/vue_system/vue_statistics/department')">部门统计</a-menu-item>
          </a-sub-menu>
        </a-menu>
      </div>
    </div>
    <div class="Auto" ref="children"></div>
  </div>
</template>

<script>
export default {
  props: ['routerProps','config','refresh'],
  data() {
    return {
      collapsed: false,
    };
  },
  methods: {
    toggleCollapsed() {
      this.collapsed = !this.collapsed;
    },
    push(path) {
      this.routerProps.history.push(path);
    }
  },
};
</script>

<style lang="less" scoped>
.Wrap {
  display: flex;
  width: 100%;
  height: 100%;

  > .Fixed {
    flex-shrink: 0;
    width: 200px;
    height: 100%;

    > .Menu {
      height: 100%;

      /deep/.ant-menu {
        height: 100%;
      }

    }
  }

  > .Auto {
    flex-grow: 1;
    min-width: 0;
    padding: 20px;
  }
}
</style>

// packages/ctsj-microfrontends-react-basiclayout-app/src/basiclayout.jsx
import React from 'react';
import { Menu } from 'antd';

import styles from './basiclayout.less';

const { SubMenu } = Menu;

/**
 * BasicLayout
 * @class BasicLayout
 * @classs BasicLayout
 */
class BasicLayout extends React.Component {
  ref = React.createRef();

  state = {
    collapsed: false,
  };

  render() {
    return (
      <div className={styles.Wrap}>
        <div className={styles.Fixed}>
          <div className={styles.Menu}>
            <Menu
              defaultSelectedKeys={['1']}
              defaultOpenKeys={['sub1']}
              mode="inline"
              theme="dark"
              inlineCollapsed={this.state.collapsed}
            >
              <Menu.Item
                key="1"
                onClick={() => {
                  this.props.history.push('/system/menu');
                }}
              >
                菜单管理
              </Menu.Item>
              <Menu.Item
                key="2"
                onClick={() => {
                  this.props.history.push('/system/role');
                }}
              >
                角色管理
              </Menu.Item>
              <Menu.Item
                key="3"
                onClick={() => {
                  this.props.history.push('/system/department');
                }}
              >
                部门管理
              </Menu.Item>
              <SubMenu key="4" title="统计">
                <Menu.Item
                  key="11"
                  onClick={() => {
                    this.props.history.push('/system/statistics/total');
                  }}
                >
                  汇总统计
                </Menu.Item>
                <Menu.Item
                  key="22"
                  onClick={() => {
                    this.props.history.push('/system/statistics/person');
                  }}
                >
                  人员统计
                </Menu.Item>
                <Menu.Item
                  key="33"
                  onClick={() => {
                    this.props.history.push('/system/statistics/department');
                  }}
                >
                  部门统计
                </Menu.Item>
              </SubMenu>
            </Menu>
          </div>
        </div>
        <div className={styles.Auto} ref={this.ref} />
      </div>
    );
  }
}

export default BasicLayout;
